 server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: api-gateway
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  cloud:
    compatibility-verifier:
      enabled: false
    discovery:
      enabled: false
    config:
      enabled: false
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 2
            statuses: SERVICE_UNAVAILABLE
            methods: GET, POST

      routes:
        # Route pour favicon.ico
        - id: faviconRoute
          uri: file:///path/to/your/favicon.ico
          predicates:
            - Path=/favicon.ico

        # Route pour les images de véhicules
        - id: vehicules-images-route
          uri: http://vehiculeservice:8082
          predicates:
            - Path=/api/vehicules/images/**
          filters:
            - RewritePath=/api/vehicules/images/(?<segment>.*),/images/${segment}

        # Route pour le microservice de gestion des véhicules
        - id: gestionVehiculeService
          uri: http://vehiculeservice:8082
          predicates:
            - Path=/api/vehicules/**
          filters:
            - StripPrefix=1

        # Route explicite pour le frontend `/vehicules`
        - id: vehiculesFrontend
          uri: forward:/vehicules
          predicates:
            - Path=/vehicules

        # Route pour le microservice de gestion des clients
        - id: clientService
          uri: http://clientservice:8081
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=1

        # Route pour le microservice de gestion des locations de véhicules
        - id: locationVehiculeService
          uri: http://locationservice:8083
          predicates:
            - Path=/api/locations/**
          filters:
            - StripPrefix=1

        # Route par défaut pour toutes les autres URLs (fallback)
        # - id: fallbackToSelf
        #   uri: http://localhost:8080
        #   predicates:
        #     - Path=/**
        #   filters:
        #     - name: PreserveHostHeader

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud.gateway: TRACE
    reactor.netty: TRACE

gateway:
  url: http://localhost:8080
