apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # URL du serveur ACME de Let's Encrypt en mode staging (test)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: oum.hanane@example.com  # <-- mon email ici
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
