apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: parkauto
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
