apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: parkauto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: saliha91700/clientimage:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
