apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: parkauto
spec:
  selector:
    app: location
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
