apiVersion: v1
kind: Service
metadata:
  name: vehicule-service
  namespace: parkauto
spec:
  selector:
    app: vehicule
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
