services:
  clientservice:
    build:
      context: ./client
    image: clientimage
    container_name: clientservice
    ports:
      - "8081:8081"
    networks:
      - gateway
    restart: always

  vehiculeservice:
    build:
      context: ./gestionvehicules
    image: gestionvehiculesimage
    container_name: vehiculeservice
    ports:
      - "8082:8082"
    networks:
      - gateway
    restart: always

  locationservice:
    build:
      context: ./gestionlocation
    image: locationimage
    container_name: locationservice
    ports:
      - "8083:8083"
    networks:
      - gateway
    restart: always

  gatewayservice:
    build:
      context: ./gateway
    image: gatewayimage
    container_name: gatewayservice
    ports:
      - "8080:8080"
    networks:
      - gateway
    restart: always

networks:
  gateway:
    driver: bridge
