-- Insertion des données
INSERT INTO "VEHICULE" ("IDVEHICULE", "ANNEEMODEL", "PRIX", "IMAGE_VEHICULE") VALUES (1, 2020, 25000.0, 'AUDI_A3_SPORTBACK_.jpeg');
INSERT INTO "VEHICULE" ("IDVEHICULE", "ANNEEMODEL", "PRIX", "IMAGE_VEHICULE") VALUES (2, 2019, 22000.0, 'BMW_SERIE_2_GRAN_TOURER.jpeg');
INSERT INTO "VEHICULE" ("IDVEHICULE", "ANNEEMODEL", "PRIX", "IMAGE_VEHICULE") VALUES (3, 2018, 18000.0, 'FIAT_500X_.jpeg');
INSERT INTO "VEHICULE" ("IDVEHICULE", "ANNEEMODEL", "PRIX", "IMAGE_VEHICULE") VALUES (4, 2021, 45000.0, 'MERCEDES_BENZ_CLASSE_C.jpeg');
INSERT INTO "VEHICULE" ("IDVEHICULE", "ANNEEMODEL", "PRIX", "IMAGE_VEHICULE") VALUES (5, 2022, 50000.0, 'BMW_X3_F25_.jpeg');
