CREATE TABLE "VEHICULE" (
    "IDVEHICULE" BIGINT PRIMARY KEY,
    "ANNEEMODEL" INT NOT NULL,
    "PRIX" DOUBLE NOT NULL,
    "IMAGE_VEHICULE" VARCHAR(255)
);

CREATE TABLE "voiture" (
    "IDVEHICULE" BIGINT PRIMARY KEY,
    FOREIGN KEY ("IDVEHICULE") REFERENCES "VEHICULE"("IDVEHICULE") ON DELETE CASCADE
);

CREATE TABLE "camion" (
    "IDVEHICULE" BIGINT PRIMARY KEY,
    FOREIGN KEY ("IDVEHICULE") REFERENCES "VEHICULE"("IDVEHICULE") ON DELETE CASCADE
);
