name: Build, Push and Test Client Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
      - '.github/workflows/client-docker.yml'

jobs:
  build-push-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/client:latest

      - name: Run container for testing
        run: |
          docker run -d -p 8080:8080 --name client-test ${{ secrets.DOCKERHUB_USERNAME }}/client:latest
          sleep 10  # Attendre que l'app démarre

      - name: Test service is up
        run: |
          curl -f http://localhost:8080 || (docker logs client-test && exit 1)
